import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";

import Provider from "@/context/provider";
import { cn } from "@/lib/utils";
import "./globals.css";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="pt-br"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="w-full px-4">
        <div className="max-w-6xl mx-auto">
          {/* cor de fundo fafafa */}
          <Provider>{children}</Provider>
        </div>
      </body>
    </html>
  );
}